all: crackme_xor crackme_hash

crackme_xor: crackme_xor.cpp
	g++ -m32 crackme_xor.cpp -o crackme_xor

crackme_hash: crackme_hash.cpp
	g++ -m32 crackme_hash.cpp -o crackme_hash

clean:
	rm -rf crackme_xor crackme_hash
